import faker
import json
import os
from random import randint as rint

fio = faker.Faker('ru_RU')  # Fake full name trio generator

storage = []
# storage = {}  # old variant for using id as a key


def generate(amt: int=100) -> None:
    """
    Takes a fake full name string generated by Faker.
    Calls phone generator and compiles a phonebook entry.
    :param amt:
    :return:
    """
    global storage
    extra = ('тов.', 'г-н', 'г-жа')
    for _ in range(amt):
        unit = {}
        line: str = fio.name()
        if line.startswith(extra):
            line = ' '.join(line.split()[1:])
        else:
            line = ' '.join(line.split())
        tmp = arrange(line)
        # unit['Name'] = tmp
        # unit['Phone'] = [phone for phone in phone_generator(rint(1, 3))]
        # storage[hash(tmp[1])] = unit
        unit['id'] = hash(tmp[1])
        unit['Name'] = tmp
        unit['Phone'] = [phone for phone in phone_generator(rint(1, 3))]
        storage.append(unit)
        del tmp, unit


def arrange(line_in: str) -> list:
    """
    Gets a line of Surname Name Father-name and arranges it in common way.
    :param line_in: str
    :return: line_in: list
    """
    suffixes = ('ов', 'ова', 'ев', 'ева', 'ив', 'ива')
    line_in = line_in.split()
    if line_in[-1].endswith(suffixes):
        line_in = [line_in[-1]] + line_in[:-1]
    return line_in


def phone_generator(amt: int) -> str:
    """
    Fake-phone number generator-function.
    :param amt:
    :return: str
    """
    for _ in range(amt):
        phn = '+7(' + str(rint(900, 999)) + ')' + str(rint(100_00_00, 999_99_99))
        yield phn


def main_local(file_name: str) -> None:
    """
    Initial starter
    :return: None
    """
    global storage
    generate()
    print(storage)
    storage = json.dumps(storage)
    with open(file_name, 'w') as out_fl:
        out_fl.write(str(storage))


def additional():
    # print(os.path.abspath('.'))
    print(os.path.commonpath([os.curdir, '.']))
    pass


textual_intro = '''
    
    Phonebook generator.
    This subprogram generates fake full names of three positions and random
    phone numbers.
    If You wish to generate new fake phonebook input "generate" (not quoted).
    Otherwise any other phrase to continue or "exit" to exit.
    
'''

print(textual_intro)

while True:
    choice = input('Make choice: ')
    if choice == 'exit':
        raise SystemExit
    elif choice == 'generate':
        file_nm = input('Input filename (extension is not required, .txt is used): ') + '.txt'
        main_local(file_nm)
    else:
        additional()

